// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmZhJ7cEu4CGMOS3IwfQyKqXicuQd1xtA',
    appId: '1:1091695753405:web:050ea083814b09ba499fd4',
    messagingSenderId: '1091695753405',
    projectId: 'agrifresh-4dd72',
    authDomain: 'agrifresh-4dd72.firebaseapp.com',
    storageBucket: 'agrifresh-4dd72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4GV10Qyn0BVtpozd0uFtAO6E7Fgv5Hts',
    appId: '1:1091695753405:android:59e6648340024c6b499fd4',
    messagingSenderId: '1091695753405',
    projectId: 'agrifresh-4dd72',
    storageBucket: 'agrifresh-4dd72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn9B5RkIT87r6qCMCwrvVTFq3zuV-v-iw',
    appId: '1:1091695753405:ios:2cd53a62f501f2a1499fd4',
    messagingSenderId: '1091695753405',
    projectId: 'agrifresh-4dd72',
    storageBucket: 'agrifresh-4dd72.appspot.com',
    iosBundleId: 'com.example.agrifresh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn9B5RkIT87r6qCMCwrvVTFq3zuV-v-iw',
    appId: '1:1091695753405:ios:2cd53a62f501f2a1499fd4',
    messagingSenderId: '1091695753405',
    projectId: 'agrifresh-4dd72',
    storageBucket: 'agrifresh-4dd72.appspot.com',
    iosBundleId: 'com.example.agrifresh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmZhJ7cEu4CGMOS3IwfQyKqXicuQd1xtA',
    appId: '1:1091695753405:web:f13322a4b89a49a8499fd4',
    messagingSenderId: '1091695753405',
    projectId: 'agrifresh-4dd72',
    authDomain: 'agrifresh-4dd72.firebaseapp.com',
    storageBucket: 'agrifresh-4dd72.appspot.com',
  );
}
